# coding: utf-8

"""
    Authress

    <p> <h2>Introduction</h2> <p>Welcome to the Authress Authorization API. <br>The Authress REST API provides the operations and resources necessary to create records, assign permissions, and verify any user in your platform.</p> <p><ul>   <li>Manage multitenant platforms and create user tenants for SSO connections.</li>   <li>Create records to assign roles and resources to grant access for users.</li>   <li>Check user access control by calling the authorization API at the right time.</li>   <li>Configure service clients to securely access services in your platform.</li> </ul></p> <p>For more in-depth scenarios check out the <a href=\"https://authress.io/knowledge-base\" target=\"_blank\">Authress knowledge base</a>.</p> </p>

    The version of the OpenAPI document: v1
    Contact: support@authress.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authress.api.user_permissions_api import UserPermissionsApi  # noqa: E501


class TestUserPermissionsApi(unittest.TestCase):
    """UserPermissionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserPermissionsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_authorize_user(self) -> None:
        """Test case for authorize_user

        Verify user authorization  # noqa: E501
        """
        pass

    def test_get_user_permissions_for_resource(self) -> None:
        """Test case for get_user_permissions_for_resource

        Get user permissions for resource  # noqa: E501
        """
        pass

    def test_get_user_resources(self) -> None:
        """Test case for get_user_resources

        List user resources  # noqa: E501
        """
        pass

    def test_get_user_roles_for_resource(self) -> None:
        """Test case for get_user_roles_for_resource

        Get user roles for resource  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
