on:
  push:
    branches:
    - main
    - master
    - 'release/**'
  pull_request:
    branches:
    - main
    - master
    - 'release/**'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up environment
      uses: actions/setup-python@v4
      with:
        python-version: 3.8.5

    - name: Set Version number
      run: |
        branchId="${GITHUB_REF/refs\/heads\/release\//}"
        buildNumber="${branchId}.${GITHUB_RUN_NUMBER}"
        sed "s/0.0.0/${buildNumber}/g" ./authress_sdk/VERSION -i
    - name: Install dependencies
      run: pip3 install -r requirements.txt -r test-requirements.txt

    - name: Run Tests
      run: nosetests

    - name: Deploy package to package repository
      uses: pypa/gh-action-pypi-publish@release/v1
      if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' && github.event_name == 'push'
      with:
        print_hash: true
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: authress_sdk/

    - name: Tag and release version
      if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' && github.event_name == 'push'
      run: |
        git tag ${GITHUB_REF/refs\/heads\/release\//}.$GITHUB_RUN_NUMBER
        git push origin ${GITHUB_REF/refs\/heads\/release\//}.$GITHUB_RUN_NUMBER

